### ISSUE TITLE
Lock Screen preventing logout/restart.

### ISSUE THREAD

**Issue by AbstractUmbra** [sheagcraig/auto_logout#7]
Hey there.
Thank you for this. It's bloody marvelous!

I just need to ask one thing - we don't use filevault in our lab, but we do have the screen locking after 15 mins of inactivity (SysPref > Security > General > 'Require Password Immediately...') which is preventing the script. Any ideas how to circumvent it?

**Comment by 64Hz** [comment]
I found a command to check if the lock screen is active and locked. I'm unsure how to add it to the Python script to add it as a rule that if it's locked, force a reboot.

`LOCK="$(python -c 'import sys,Quartz; d=Quartz.CGSessionCopyCurrentDictionary(); print d')"`

**Comment by sheagcraig** [comment]
Wow, totally missed this one. My apologies. In 2019, are you still even able to have Mac labs :( ?

The current code uses mouse and keyboard activity to determine whether to shutdown / reboot. It should bypass the screen lock without issue. If you're still interested in this, let me know!
