### ISSUE TITLE
Shutdown error

### ISSUE THREAD

**Issue by ABrdfd** [sheagcraig/auto_logout#8]
Greetings, 

Just started trying to use your script, and had errors related to shutdown.  I found the following section did not specify sudo -u root:

def shutdown():
    """Shutdown the computer immediately."""
    result = subprocess.check_output(["/sbin/shutdown", "-h", "now"])
    syslog.syslog(syslog.LOG_ALERT, result)

and amending the script to the following it fixed it in my case:

def shutdown():
    """Shutdown the computer immediately."""
    result = subprocess.check_output(["sudo", "-u", "root", "/sbin/shutdown", "-h", "now"])
    syslog.syslog(syslog.LOG_ALERT, result)

**Comment by sheagcraig** [comment]
Ah, it appears that I never used shutdown and never noticed this! Please feel free to drop me a PR with that change and I'll get that out for everyone.
